version: '3.7'

services:

  node:
    image: "node:16-slim"
    container_name: dd-node
    working_dir: /home/node/app
    environment:
      # Set environment variable used by dd-trace library
      - DD_SERVICE=snoopy
      - DD_VERSION=0.1.0
      - DD_TAGS=owner:ddog,deployment:blue
      - DD_AGENT_HOST=datadog-agent # container_name for agent
      - DD_TRACE_AGENT_PORT=8126 # default port for APM
      # Set environment variable used by node-dogstatsd library
      - DD_STATSD_AGENT_PORT=8125 # default for statsd
    volumes:
      - ./:/home/node/app
    ports:
      - 3000:3000/tcp
    # expose:
    #   - "8080"
    # depends_on:
    #   - mongo
    command: "npm run start"
    labels:
        com.datadoghq.ad.logs: '[{"source":"nodejs","service":"snoopy"}]'

  nginx:
    image: nginx
    container_name: dd-nginx
    ports:
        - "8888:80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - node
    labels:
        com.datadoghq.ad.check_names: '["nginx"]'
        com.datadoghq.ad.init_configs: '[{}]'
        com.datadoghq.ad.instances: '[{"nginx_status_url":"http://%%host%%:81/nginx_status"}]'
        com.datadoghq.ad.logs: '[{"source":"nginx","service":"snoopy-nginx","sourcecategory":"http_web_access"}]'

  datadog:
    container_name: datadog-agent
    image: datadog/agent:latest
    environment:
      ## GLOBALS
      - DD_API_KEY
      - DD_SITE
      - DD_HOSTNAME=localpro
      - DD_TAGS=env:local owner:ddog
      ## APM https://docs.datadoghq.com/agent/docker/apm/
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_APM_IGNORE_RESOURCES=GET /static, GET /health # Exclude resources that are not necessary to track and maybe too verbose
      ## LOGS https://docs.datadoghq.com/agent/docker/log/
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      ## LIVE PROCESSES https://docs.datadoghq.com/graphing/infrastructure/process/?tab=docker
      - DD_PROCESS_AGENT_ENABLED=true
      ## DOGSTATSD
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
    ports:
      - 8126:8126/tcp # APM available from any host
      - 8125:8125/udp # Dogstatsd
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
     - /etc/passwd:/etc/passwd:ro # LIVE PROCESSES

