version: '3.7'

services:

  # springbootapp:
  #   container_name: springbootapp
  #   image: openjdk:8
  #   environment:
  #     - TEAM=ddog_power
  #     - DD_AGENT_HOST=datadog-agent
  #   volumes:
  #     - ./:/user/src/myapp
  #   ports:
  #     - 8080:8080
  #   command: "java -javaagent:/user/src/myapp/dd-java-agent-0.52.0.jar -Ddd.service=dd-partner-demo	-Ddd.version=0.0.1 -Ddd.tags=partner.class:workshop,partner.app:javaspringboot-dummy,owner:ddog,customer:abc,team:team -jar /user/src/myapp/build/libs/demo-0.0.1-SNAPSHOT.jar"
  #   labels:
  #     com.springboot.team: "ddog_flower"

  datadog:
    container_name: datadog-agent
    image: datadog/agent:latest
    environment:
      ## GLOBALS
      - DD_API_KEY # The value will be taken from the .env file
      - DD_SITE # The value will be taken from the .env file
      - DD_HOSTNAME=localpro
      - DD_TAGS=env:local owner:narbais
      - DD_AC_EXCLUDE=name:datadog-agent # exclude this container from data collection
      ## TAGS
      # - DD_DOCKER_LABELS_AS_TAGS=true
      # - DD_DOCKER_ENV_AS_TAGS=true
      - DD_DOCKER_ENV_AS_TAGS='{"TEAM":"team"}'
      - DD_DOCKER_LABELS_AS_TAGS='{"com.springboot.team":"team"}'
      ## APM https://docs.datadoghq.com/agent/docker/apm/
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      ## LOGS https://docs.datadoghq.com/agent/docker/log/
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      ## LIVE PROCESSES https://docs.datadoghq.com/graphing/infrastructure/process/?tab=docker
      - DD_PROCESS_AGENT_ENABLED=true
      ## DOGSTATSD
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
    ports:
      - 8126:8126/tcp # APM available from any host
      - 8125:8125/udp # Dogstatsd
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
     - /etc/passwd:/etc/passwd:ro # LIVE PROCESSES
